### ISSUE TITLE
configure: entitlements not generated, infoPlist not updating

### ISSUE THREAD

**Issue by cronn-leonn** [ionic-team/capacitor-configure#14]
When I use `entitlements` like shown in the example [`basic.yml`](https://github.com/ionic-team/capacitor-configure/blob/main/examples/basic.yml), no changes are made to my `.entitlements` file.
```yaml
        entitlements:
          - keychain-access-groups:
              [
                "$BUNDLE_ID",
                "com.microsoft.intune.mam",
                "com.microsoft.adalcache",
              ]
```

Also: The structure of the `Info.plist` that Xcode generated is:
```xml
// ...
<plist version="1.0">
<dict>
	<key>NSAppClip</key>
	<dict>
		<key>NSAppClipRequestEphemeralUserNotification</key>
		<false/>
		<key>NSAppClipRequestLocationConfirmation</key>
		<false/>
	</dict>
// ...
</dict>
</plist>
```

So I assumed that `infoPlist` should also contain a dictionary (`NSAppClip` without the `-`) and not a list in the yaml file, like:

```yaml
        infoPlist:
          NSAppClip:
            NSAppClipRequestEphemeralUserNotification: false
            NSAppClipRequestLocationConfirmation: false
```
But this leads to the error:

```

[error] entries is not iterable
Unhandled Rejection TypeError: entries is not iterable
    at execute (/node_modules/@capacitor/configure/dist/operations/ios/plist.js:6:25)
    at runOperation (/node_modules/@capacitor/configure/dist/operations/index.js:45:16)
    at executeOperations (/node_modules/@capacitor/configure/dist/tasks/run.js:60:40)
    at async runCommand (/node_modules/@capacitor/configure/dist/tasks/run.js:28:9)
    at async /node_modules/@capacitor/configure/dist/index.js:51:9
    at async Command.<anonymous> (/node_modules/@capacitor/configure/dist/util/cli.js:31:13)
/node_modules/@capacitor/configure/bin/cap-config:13
  throw err;
  ^

```

When I use `infoPlist` like the following, it writes the desired result to the `Info.plist` file, but only if the keys do not already exist (If I delete them from the file manually beforehand). Is this on purpose?

```yaml
        infoPlist:
          - NSAppClip:
              NSAppClipRequestEphemeralUserNotification: true
              NSAppClipRequestLocationConfirmation: false
```
