### ISSUE TITLE
Running yml file without confirmation does not configure Android project

### ISSUE THREAD

**Issue by marioshtika** [ionic-team/capacitor-configure#15]
Hello,

I am using the below yml file

```
vars:
  VERSION:
    default: 1.0.1

platforms:
  ios:
    targets:
      App:
        version: $VERSION

  android:
    versionName: $VERSION
```

If I run 
```
npx cap-config run config.yml
```
it is working fine

But if I want to run the yml file without confirmation using the `-y`
```
npx cap-config run config.yml -y
```

The Android `version name` it is not being updated.

Am I doing something wrong, should I do something different or is something there that it is not waiting for the change to finish.

Thank you in advance.
