### ISSUE TITLE
bug: iOS buildNumber only allows number

### ISSUE THREAD

**Issue by tobiasmuecksch** [ionic-team/capacitor-configure#20]
Up until now, I always used the same version identifier for `MARKETING_VERSION` and `CURRENT_PROJECT_VERSION`.

Therefore I expected that setting for example `2.2.2` as `buildNumber`, would set this value for  `CURRENT_PROJECT_VERSION` in the `project.pbxproj` file.

Instead it sets `1` as value. I assume, that the input is casted to the number type, which seems to resolve to `1` by default, if the input does not match the expected type.

This is an excerpt of my `config.yml`
```
platforms:
  ios:
    targets:
      App:
        bundleId: com.my-cool-app
        version: 2.2.2
        buildNumber: 2.2.2
        incrementBuild: true
```

This is the current result in the `project.pbxproj` file:
```
CURRENT_PROJECT_VERSION = 1;
```

This is what I expected instead:
```
CURRENT_PROJECT_VERSION = 2.2.2;
```

Maybe I'm breaking some convention which I'm not aware of (but Xcode accepts that value without any warning). In that case I'd suggest to show a warning, in order to prevent future obsolete issue tickets.
