### ISSUE TITLE
how to use base64 decode? 

### ISSUE THREAD

**Issue by reslear** [ionic-team/capacitor-configure#203]
good afternoon, @mlynch thx for https://github.com/ionic-team/trapeze/issues/105 :) 
do we have some kind of easy way to decode a base64 string?

for example `$GOOGLE_SERVICE_PLIST_RAW` it's more convenient to store in base64, but you have to decode it.

I suggest to do it:
 1. automatically value -> base64 === value 
 2. or add `from` key with enum`base64`. 
 
```yml
platforms:
  ios:
    targets:
      App:
        plist:          
          - file: GoogleService-Info.plist
            xml: $GOOGLE_SERVICE_PLIST_RAW
            # add `from` attribute 
            from: base64
```

**nodejs**:

```ts
const value = Buffer.from(process.env.GOOGLE_SERVICE_PLIST_RAW, 'base64').toString(
  'ascii'
)
```

**browser**:

```ts
const value = atob(process.env.GOOGLE_SERVICE_PLIST_RAW)
```
