### ISSUE TITLE
configure: Info.plist stays unchanged

### ISSUE THREAD

**Issue by tobiasmuecksch** [ionic-team/capacitor-configure#23]
# Current behavior
When running `cap-configure` it seems to ignore my `infoPlist`-settings

```
    infoPlist:
      - CFBundleDevelopmentRegion: de_DE
      - NSCameraUsageDescription: Hochladen von Bildern für Chat und Profil.
      - NSPhotoLibraryAddUsageDescription: Speichern von Bildern aus dem Chat-Verlauf.
      - NSPhotoLibraryUsageDescription: Hochladen von Bildern für Chat und Profil.
      - ITSAppUsesNonExemptEncryption: false
```

# Expected behavior
I expected it to add the properties above to the `Info.plist`-file

# Version
I observed this behavior in version `1.0.20`

# Reproduction
I've created a demo repo for you to quickly reproduce.

https://github.com/tobiasmuecksch/cap-configure-problem-demo

1. clone repo
2. run `npm run init`
    - _Info: This task installs npm packages, adds the `ios` and `android` platforms and runs `cap-configure`_

Then check the `ios/App/App/Info.plist`-file, and you'll see, that none of the settings above are set.
