### ISSUE TITLE
configure: `applicationId` in `build.gradle` stays unchanged

### ISSUE THREAD

**Issue by tobiasmuecksch** [ionic-team/capacitor-configure#24]
# Current behavior
When running `cap-configure` it seems to ignore the applicationId for android

`plaftorm-config.yml`
```
vars:
  PACKAGE_NAME_ANDROID:
    default: com.capconfigure.demoandroid

  android:
    packageName: $PACKAGE_NAME_ANDROID
    versionName: 2.2.2
    versionCode: 222
```

<img width="1476" alt="Bildschirmfoto 2021-11-30 um 07 23 02" src="https://user-images.githubusercontent.com/1294854/143996772-a7278d0e-a471-4e60-b8a3-82f3f434528c.png">

# Version
I observed this behavior in version `1.0.20`

# Reproduction
I've created a demo repo for you to quickly reproduce.

https://github.com/tobiasmuecksch/cap-configure-problem-demo

1. clone repo
2. run `npm run init`
    - _Info: This task installs npm packages, adds the `ios` and `android` platforms and runs `cap-configure`_

Then check the `android/app/build.gradle`-file, and you'll see, that the `applicationId` is not updated correctly.
