### ISSUE TITLE
configure: iOS bundleId is not reflected in Xcode

### ISSUE THREAD

**Issue by tobiasmuecksch** [ionic-team/capacitor-configure#25]
# Current behavior
When running `cap-configure` it seems to ignore my `bundleId`-setting for iOS.

```
vars:
  BUNDLE_ID_IOS:
    default: com.cap-configure.demo-ios

platforms:
  ios:
    targets:
      App:
        bundleId: $BUNDLE_ID_IOS
```

# Screenshot

<img width="693" alt="Bildschirmfoto 2021-11-30 um 17 55 57" src="https://user-images.githubusercontent.com/1294854/144092211-dd8b0d74-bf2e-4f13-9fba-603c37292245.png">

# Version
I observed this behavior in version `1.0.21`

# Reproduction
I've created a demo repo for you to quickly reproduce.

https://github.com/tobiasmuecksch/cap-configure-problem-demo

1. clone repo
2. run `npm run init`
    - _Info: This task installs npm packages, adds the `ios` and `android` platforms and runs `cap-configure`_

Then open Xcode `ionic cap open ios` and see, that the bundle identifier is not the same as in the yml file.
