### ISSUE TITLE
Figure out if paths in yaml should be relative to cwd or to file dir

### ISSUE THREAD

**Issue by mlynch** [ionic-team/capacitor-configure#3]
ex:

```yaml
      - path: drawable
        file: icon.png
        source: ../common/test/fixtures/icon.png
```
