### ISSUE TITLE
It is not possible to set UISupportedInterfaceOrientations

### ISSUE THREAD

**Issue by kentora** [ionic-team/capacitor-configure#33]
I am trying to set the UISupportedInterfaceOrientations (and UISupportedInterfaceOrientations~ipad), but setting
```
          - UISupportedInterfaceOrientations:
              - UIInterfaceOrientationPortrait
          - UISupportedInterfaceOrientations~ipad:
              - UIInterfaceOrientationPortrait
```

in yaml file has no effects, as long as info.plist has a UISupportedInterfaceOrientations entry already. I suspect the reason is that the entries are merged into the existing, when in reality (At least for these two cases) they should override.

Maybe there should be a way to specify that the array should be overridden in the yaml file, to avoid having to maintain a list over entries that should be overridden as opposed to merged.

**Comment by mlynch** [comment]
Similar question on your other issue: which version are you on? Fixed a number of plist issues recently and maybe created a few in the process 😩

**Comment by kentora** [comment]
I'm on 1.0.22 :)

**Comment by mlynch** [comment]
So your expectation here would be to totally overwrite the entries? i.e. go from a list of three default orientations to your single specified one?

**Comment by kentora** [comment]
Yes, although I think that expected behavior might be limited to this exact case - at least I have not identified any more yet

**Comment by mlynch** [comment]
Got it so I think this is more of an enhancement/change to enable to either merge or overwrite the items. Will think about a way to express this in the yaml 🤔

**Comment by mlynch** [comment]
Okay added support to the underlying project API for this:

```typescript
    await project.ios?.updateInfoPlist('App', 'Debug', {
      UISupportedInterfaceOrientations: [
        'UIInterfaceOrientationPortrait'
      ]
    }, {
      replace: true
    });
```

Just need to figure out the yaml/configure side of this from a DX standpoint

**Comment by mlynch** [comment]
I think I'm going to rethink the `infoPlist` option in the `yaml` and nest the entries one level deeper and also give the ability to specify the plist, something like

```
        plist:
          replace: true
          # Optional: specify the file
          file: App/My.plist
          entries:
            - NSFaceIDUsageDescription: Use Face ID to authenticate yourself and login
            - CFBundleURLTypes:
                - CFBundleURLSchemes:
                    - 
```

**Comment by mlynch** [comment]
Fixed in 1.0.24, thanks!

Make sure to use the new plist format as shown in my comment above. `infoPlist` will be transformed to the new format, however.

**Comment by kentora** [comment]
> I think I'm going to rethink the `infoPlist` option in the `yaml` and nest the entries one level deeper and also give the ability to specify the plist, something like (note: you'd be able to have multiple `plist` entries here so you could do some that replace and some that merge)
> 
> ```
>         plist:
>           replace: true
>           # Optional: specify the file
>           file: App/My.plist
>           entries:
>             - NSFaceIDUsageDescription: Use Face ID to authenticate yourself and login
>             - CFBundleURLTypes:
>                 - CFBundleURLSchemes:
>                     - 
> ```

Could you provide an example of how one would specify multiple plist entries? Having two plist: lines at the same level causes configure to output an error. Right now i use infoPlist for merging and plist: replace: true for replacing, as a workaround.

**Comment by mlynch** [comment]
Gah, sorry about that. I'm going to make one more change as keys have to be unique

**Comment by mlynch** [comment]
Okay try 1.0.25, it now supports an array of entries. You can also just pass a single entry as an object and that will work, too

```yaml
plist:
  - replace: true
     entries:
       - NSFaceIDUsageDescription: blah
```
