### ISSUE TITLE
how to use dynamic variables for simulator or xcode

### ISSUE THREAD

**Issue by reslear** [ionic-team/capacitor-configure#39]
```yml
vars:
 CI_BUILD_NUMBER:
  BUNDLE_ID:
  REVERSED_CLIENT_ID:
  DOMAIN:
  APP_NAME:

platforms:
  ios:
    targets:
      App:
        bundleId: '"$(BUNDLE_ID)"'
        buildNumber: '"$(CI_BUILD_NUMBER)"'
        productName: '"$(TARGET_NAME)"'
        displayName: "$(APP_NAME)"
```
for example in appflow is working 

but is open this in xcode for simulator, have clean fileds

```sh
BUNDLE_ID=com.app.app npx cap open ios
```

<img width="786" alt="Screenshot 2022-01-04 at 14 14 02" src="https://user-images.githubusercontent.com/12596485/148017055-fcdad333-9f35-47b9-b0dd-242c3d71438d.png">
