### ISSUE TITLE
Using YAML to modify build.gradle

### ISSUE THREAD

**Issue by sanderschnydrig** [ionic-team/capacitor-configure#47]
If this is already supported I haven't been able to find how to modify values in app/build.gradle.

```yaml
  android:
    packageName: $APP_IDENTIFIER
    versionName: $APP_VERSION
    versionCode: $BUILD_NUMBER_ANDROID

    gradle:
      - file: app/build.gradle
        target:
          android:
            defaultConfig:
        insert: |
          manifestPlaceholders = [baseUrl:"$BASE_URL"]
```

I'm trying to use the ENV variable that I imported in the YAML to set a baseUrl variable that I can use in the AndroidManifest.xml (since I didn't find how to replace values there, only inject new ones). But instead of adding/replacing, it always adds a new entry. So whenever I switch my deploy target for the app, I end up with multiple variables as the old ones dont get replaced.

Is this possible with either YAML or TS or do I have to use shell or node script for now?
